// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqvrfirzbarsfhclbmdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdnJmaXJ6YmFyc2ZoY2xibWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTcxODUsImV4cCI6MjA1NTI3MzE4NX0.7ehDoNgbeCrtY7iEuR3RmltDPWaFSe_pEgyFsUyCENY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);